language: generic
dist: xenial

env:
    - UID=1000 USER=qgis_user

services:
  - docker

before_install:
  - docker-compose build

script:
  # We set the QT_QPA_PLATFORM to run the tests on a headless server: http://doc.qt.io/qt-5/embedded-linux.html
  - docker-compose run -e QT_QPA_PLATFORM=offscreen qgis-desktop make test
  - docker-compose run qgis-desktop make pep8

notifications:
    email: false